
import net.fabricmc.loom.api.LoomGradleExtensionAPI
import net.fabricmc.loom.task.RemapJarTask
import java.text.SimpleDateFormat
import java.util.*

plugins {
    id("fabric-loom") version "1.14-SNAPSHOT"
    id("com.github.gmazzo.buildconfig") version "5.3.5"
    id("com.gradleup.shadow") version "9.0.0-beta4"
    java
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

base {
    archivesName.set(property("archives_base_name").toString())
}

version = property("mod_version")!!
group = property("maven_group")!!

buildConfig {
    buildConfigField("String", "VERSION", "\"${property("mod_version")}\"")
    buildConfigField("String", "BUILD_IDENTIFIER", "\"${property("build_identifier")}\"")
    buildConfigField("String", "BUILD_TIME", "\"${SimpleDateFormat("MM/dd/yyyy HH:mm").format(Date())}\"")

    packageName("dev.mzc.client")
    useJavaOutput()
    generateAtSync.set(true)
    documentation.set("Generated by BuildConfig plugin")
}

configure<LoomGradleExtensionAPI> {
    accessWidenerPath.set(file("src/main/resources/sakura.accesswidener"))
    mixin {
        defaultRefmapName.set("Sakura-refmap.json")
    }
}

sourceSets["main"].java.srcDirs("build/gen/buildconfig/src/main")

repositories {
    //mavenLocal()
    flatDir {
        dirs("libs")
    }
    maven {
        name = "AliyunPublic"
        url = uri("https://maven.aliyun.com/repository/public")
    }
    maven {
        name = "AliyunGoogle"
        url = uri("https://maven.aliyun.com/repository/google")
    }
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
    maven("https://impactdevelopment.github.io/maven/")
    maven("https://maven.fabricmc.net/")
    //maven("https://raw.githubusercontent.com/cabaletta/baritone/master/maven/")
    maven("https://maven.isxander.dev/")
    maven("https://maven.meteordev.org/releases")
    maven("https://maven.meteordev.org/snapshots")
}

dependencies {
    "minecraft"("com.mojang:minecraft:${property("minecraft_version")}")
    "mappings"("net.fabricmc:yarn:${property("yarn_version")}:v2")

    "modImplementation"("net.fabricmc:fabric-loader:${property("loader_version")}")
    "modImplementation"("net.fabricmc.fabric-api:fabric-api:${property("fabric_version")}")
    "modImplementation"(files("libs/baritone-api-fabric-1.21.11.jar"))
    implementation(include("nether-pathfinder:nether-pathfinder:1.4.1")!!)

    implementation(include("meteordevelopment:orbit:${property("orbit_version")}")!!)
    implementation(include("org.apache.httpcomponents:httpclient:4.5.14")!!)
    implementation(include("org.apache.httpcomponents:httpcore:4.4.16")!!)
    implementation(include("commons-logging:commons-logging:1.2")!!)
    implementation(include("commons-codec:commons-codec:1.15")!!)

    // NanoVG 运行库
    val lwjglVersion = property("nanovg_version")
    implementation(include("org.lwjgl:lwjgl-nanovg:$lwjglVersion")!!)

    // 跨平台 Natives 支持
    val platforms = listOf(
        "natives-windows",
        "natives-macos",
        "natives-macos-arm64",
        "natives-linux",
        "natives-linux-arm64"
    )

    platforms.forEach { platform ->
        runtimeOnly(include("org.lwjgl:lwjgl:$lwjglVersion:$platform")!!)
        runtimeOnly(include("org.lwjgl:lwjgl-nanovg:$lwjglVersion:$platform")!!)
        runtimeOnly(include("org.lwjgl:lwjgl-opengles:$lwjglVersion:$platform")!!)
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.processResources {
    inputs.property("version", project.version)
    filesMatching("fabric.mod.json") {
        expand(project.properties)
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.release.set(21)
    options.encoding = "UTF-8"
    dependsOn("generateBuildConfig")
}

val isMyHome = run {
    val userHome = System.getProperty("user.home") ?: ""
    val normalized = userHome.replace('\\', '/')
    userHome == "L3MonKe" || normalized.endsWith("/L3MonKe")
}

val minecraftModsDir = file("C:/Users/L3MonKe/Desktop/MC/.minecraft/versions/1.21.11-Fabric 0.18.2/mods")

val copyJarToMinecraftMods = tasks.register<Copy>("copyJarToMinecraftMods") {
    group = "distribution"

    val remapJar = tasks.named<RemapJarTask>("remapJar")
    dependsOn(remapJar)

    onlyIf { isMyHome }

    from(remapJar.flatMap { it.archiveFile })
    into(minecraftModsDir)
}

tasks.named("build") {
    finalizedBy(copyJarToMinecraftMods)
}

tasks.jar {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.register("buildClientOnly") {
    doFirst {
        tasks.findByName("remapLoader")?.enabled = false
    }
    finalizedBy("build")
}

sourceSets {
    create("authServer") {
        java.srcDir("server/src/main/java")
    }
}

tasks.register<JavaExec>("runAuthServer") {
    group = "application"
    description = "Run MZC Auth Server management window"

    val ss = sourceSets["authServer"]
    classpath = ss.runtimeClasspath
    mainClass.set("server.Main")
    dependsOn(tasks.named(ss.classesTaskName))
}

tasks.register<Jar>("authServerJar") {
    group = "build"
    description = "Builds the Auth Server JAR"
    archiveBaseName.set("MZC-AuthServer")
    archiveVersion.set(project.version.toString())
    
    val ss = sourceSets["authServer"]
    from(ss.output)
    
    manifest {
        attributes["Main-Class"] = "server.Main"
    }
}
