systemProp.http.sslVerify=false
systemProp.https.sslVerify=false
minecraft_version=1.21.11
yarn_version=1.21.11+build.3
loader_version=0.18.2

mod_version=V1.5.0
build_identifier=Dev
maven_group=dev.mzc
archives_base_name=trollhack

fabric_version=0.140.0+1.21.11
baritone_api_version=1.13.1

orbit_version=0.2.3
nanovg_version=3.3.3
